<?php include('inc/header.php');?>

<div class="banner-area">
    <img alt="" src="images/banner/in-7.png">
    <h1>Integrated Sustainable Development Project</h1>
</div>

<section class="inner-area">
    <div class="container">
       <div class="inner-box">
            <h6>
                In order to improve the socio-economic condition of the poor and ultra-poor people of project area integrated sustainable development project, (ISDP) Phase-3 has been undertaken. To implement this program various types of activities undertaken for achieving project objectives. The activities are sponsorship, Orphanage hostel, education of orphan children, technical education, awareness development for child rights, health care, safe water supply, and sanitation and tree plantation etc. Satkhira is one of the costal district of Bangladesh. It is a disaster porne district, where natural calamities are frequently destroy the houses, crops, cattles in each year and make the people more vulnerable. Women Rights are violating among poor community in a alarming rate. As a result, divorce rate is increasing day by day. The husbands usually divorced their wives and leave them. The divorced women often get married to a second husband. Due to this kind of nature of relationship, their children become victims and get admission into orphanages. They have no ability to live in the world as a human being. In this context, Nobo Jibon has started Sponsorship Programme to support those children. Sponsorship Programme is being implemented into two ways i.e. through providing residential facilities and non residential support. SNEHO NIR (residential facility) has established for them at Nobo Jibon office complex, where the sponsorship children are living with the food, cloths, general education, treatment allowance and materials. <br><br>

                On the other hand, some orphans have with relativities houses, who are getting educational allowances and education materias from Nobo Jibon. During the reporting period NJ has supported (1500) orphan and ultra-poor children. Education is the focal activity of this program. Two types of education program have been conducted during this period for the activities. The education programs were (i) Formal education and (ii) Technical education. Under the formal education, necessary support has provided to 620 sponsored children. The supports were educational allowances, school dress, and educational materials including school bag. In order to develop skills of young girls, divorced women, unmarried poor women, students and unemployed people Vocational training programme has been started. Under this programme Nobo Jibon are providing tailoring, carpenters, mechanical, refrezeration & air condition, mobile phone servicing, computer and automobiles training programmes with all necessary equipment and aids. A professional and skilled trainers team has been engaged for providing vocational training, participants are getting involved in various types of income generating activities and new jobs. This helps them to become self- dependent and they can manage their family independently. A total of 210 participants have completed vocational training on different trades like Mechanical, Electrical, Tailoring and Computer. NJ believes that parents/guardians plays vital role in child development. Considering this issue, NJ has integrated parents/guardians of the sponsored children with this program and various types of development program has conducted involving them during the reporting period. The development oriental programs were Tree plantation, financial support for IGA program, financial support for goat rearing, Shallow tube well installation, Deep tube well installation, sanitary latrine installation and Lunch distribution.
            </h6>
        </div>
    </div>
</section>

<?php include('inc/footer.php');?>